
services:

  githubactionscicdexamplewebapinet:
    image: kraftcoding/githubactionscicdexamplewebapinet:master
    container_name: WebAPI-.NET-8
    build:
      context: .
      dockerfile: Github-Actions-CI-CD-Example-WebAPI-.NET-8/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:8080
       # - ASPNETCORE_URLS=https://+:8081 (to provide certificates are needed)
    ports:
        - "8080:8080"
       # - "8081:8081" (to provide certificates are needed)   

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: WebAPI-.NET-8
    # command: --interval 30 WebAPI-.NET-8   
    
        