
services:

  githubactionscicdexamplewebapinet:
    image: kraftcoding/githubactionscicdexamplewebapinet:main
    container_name: WebAPI-.NET-8
    build:
      context: .
      dockerfile: Github-Actions-CI-CD-Example-WebAPI-.NET-8/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:8080
       # - ASPNETCORE_URLS=https://+:8081 (to provide certificates are needed)
    ports:
        - "8080:8080"
       # - "8081:8081" (to provide certificates are needed)
    networks:
      - webapi-net
    depends_on: 
      - watchtower

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 kraftcoding/githubactionscicdexamplewebapinet:main   
    networks:
      webapi-net:
        driver_opts:
          com.docker.network.bridge.name: webapi-bridge